// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Habitify_protocol.proto

#include "Habitify_protocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Habitify {
namespace Communication {
PROTOBUF_CONSTEXPR Node::Node(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.metadata_)*/nullptr
  , /*decltype(_impl_.data_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct NodeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NodeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NodeDefaultTypeInternal() {}
  union {
    Node _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NodeDefaultTypeInternal _Node_default_instance_;
PROTOBUF_CONSTEXPR NodeMetadata::NodeMetadata(
    ::_pbi::ConstantInitialized) {}
struct NodeMetadataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NodeMetadataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NodeMetadataDefaultTypeInternal() {}
  union {
    NodeMetadata _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NodeMetadataDefaultTypeInternal _NodeMetadata_default_instance_;
PROTOBUF_CONSTEXPR NodeData::NodeData(
    ::_pbi::ConstantInitialized) {}
struct NodeDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NodeDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NodeDataDefaultTypeInternal() {}
  union {
    NodeData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NodeDataDefaultTypeInternal _NodeData_default_instance_;
PROTOBUF_CONSTEXPR Id::Id(
    ::_pbi::ConstantInitialized) {}
struct IdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~IdDefaultTypeInternal() {}
  union {
    Id _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IdDefaultTypeInternal _Id_default_instance_;
}  // namespace Communication
}  // namespace Habitify
static ::_pb::Metadata file_level_metadata_Habitify_5fprotocol_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Habitify_5fprotocol_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Habitify_5fprotocol_2eproto = nullptr;

const uint32_t TableStruct_Habitify_5fprotocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Habitify::Communication::Node, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Habitify::Communication::Node, _impl_.metadata_),
  PROTOBUF_FIELD_OFFSET(::Habitify::Communication::Node, _impl_.data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Habitify::Communication::NodeMetadata, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Habitify::Communication::NodeData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Habitify::Communication::Id, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Habitify::Communication::Node)},
  { 8, -1, -1, sizeof(::Habitify::Communication::NodeMetadata)},
  { 14, -1, -1, sizeof(::Habitify::Communication::NodeData)},
  { 20, -1, -1, sizeof(::Habitify::Communication::Id)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Habitify::Communication::_Node_default_instance_._instance,
  &::Habitify::Communication::_NodeMetadata_default_instance_._instance,
  &::Habitify::Communication::_NodeData_default_instance_._instance,
  &::Habitify::Communication::_Id_default_instance_._instance,
};

const char descriptor_table_protodef_Habitify_5fprotocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027Habitify_protocol.proto\022\026Habitify.Comm"
  "unication\"n\n\004Node\0226\n\010metadata\030\001 \001(\0132$.Ha"
  "bitify.Communication.NodeMetadata\022.\n\004dat"
  "a\030\002 \001(\0132 .Habitify.Communication.NodeDat"
  "a\"\016\n\014NodeMetadata\"\n\n\010NodeData\"\004\n\002Id2R\n\016H"
  "abitifyServer\022@\n\004Ping\022\032.Habitify.Communi"
  "cation.Id\032\032.Habitify.Communication.Id\"\000b"
  "\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_Habitify_5fprotocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Habitify_5fprotocol_2eproto = {
    false, false, 287, descriptor_table_protodef_Habitify_5fprotocol_2eproto,
    "Habitify_protocol.proto",
    &descriptor_table_Habitify_5fprotocol_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_Habitify_5fprotocol_2eproto::offsets,
    file_level_metadata_Habitify_5fprotocol_2eproto, file_level_enum_descriptors_Habitify_5fprotocol_2eproto,
    file_level_service_descriptors_Habitify_5fprotocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Habitify_5fprotocol_2eproto_getter() {
  return &descriptor_table_Habitify_5fprotocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Habitify_5fprotocol_2eproto(&descriptor_table_Habitify_5fprotocol_2eproto);
namespace Habitify {
namespace Communication {

// ===================================================================

class Node::_Internal {
 public:
  static const ::Habitify::Communication::NodeMetadata& metadata(const Node* msg);
  static const ::Habitify::Communication::NodeData& data(const Node* msg);
};

const ::Habitify::Communication::NodeMetadata&
Node::_Internal::metadata(const Node* msg) {
  return *msg->_impl_.metadata_;
}
const ::Habitify::Communication::NodeData&
Node::_Internal::data(const Node* msg) {
  return *msg->_impl_.data_;
}
Node::Node(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Habitify.Communication.Node)
}
Node::Node(const Node& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Node* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.metadata_){nullptr}
    , decltype(_impl_.data_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_metadata()) {
    _this->_impl_.metadata_ = new ::Habitify::Communication::NodeMetadata(*from._impl_.metadata_);
  }
  if (from._internal_has_data()) {
    _this->_impl_.data_ = new ::Habitify::Communication::NodeData(*from._impl_.data_);
  }
  // @@protoc_insertion_point(copy_constructor:Habitify.Communication.Node)
}

inline void Node::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.metadata_){nullptr}
    , decltype(_impl_.data_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Node::~Node() {
  // @@protoc_insertion_point(destructor:Habitify.Communication.Node)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Node::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.metadata_;
  if (this != internal_default_instance()) delete _impl_.data_;
}

void Node::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Node::Clear() {
// @@protoc_insertion_point(message_clear_start:Habitify.Communication.Node)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.metadata_ != nullptr) {
    delete _impl_.metadata_;
  }
  _impl_.metadata_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.data_ != nullptr) {
    delete _impl_.data_;
  }
  _impl_.data_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Node::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Habitify.Communication.NodeMetadata metadata = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_metadata(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Habitify.Communication.NodeData data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_data(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Node::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Habitify.Communication.Node)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Habitify.Communication.NodeMetadata metadata = 1;
  if (this->_internal_has_metadata()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::metadata(this),
        _Internal::metadata(this).GetCachedSize(), target, stream);
  }

  // .Habitify.Communication.NodeData data = 2;
  if (this->_internal_has_data()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::data(this),
        _Internal::data(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Habitify.Communication.Node)
  return target;
}

size_t Node::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Habitify.Communication.Node)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Habitify.Communication.NodeMetadata metadata = 1;
  if (this->_internal_has_metadata()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.metadata_);
  }

  // .Habitify.Communication.NodeData data = 2;
  if (this->_internal_has_data()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.data_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Node::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Node::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Node::GetClassData() const { return &_class_data_; }


void Node::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Node*>(&to_msg);
  auto& from = static_cast<const Node&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Habitify.Communication.Node)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_metadata()) {
    _this->_internal_mutable_metadata()->::Habitify::Communication::NodeMetadata::MergeFrom(
        from._internal_metadata());
  }
  if (from._internal_has_data()) {
    _this->_internal_mutable_data()->::Habitify::Communication::NodeData::MergeFrom(
        from._internal_data());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Node::CopyFrom(const Node& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Habitify.Communication.Node)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Node::IsInitialized() const {
  return true;
}

void Node::InternalSwap(Node* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Node, _impl_.data_)
      + sizeof(Node::_impl_.data_)
      - PROTOBUF_FIELD_OFFSET(Node, _impl_.metadata_)>(
          reinterpret_cast<char*>(&_impl_.metadata_),
          reinterpret_cast<char*>(&other->_impl_.metadata_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Node::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Habitify_5fprotocol_2eproto_getter, &descriptor_table_Habitify_5fprotocol_2eproto_once,
      file_level_metadata_Habitify_5fprotocol_2eproto[0]);
}

// ===================================================================

class NodeMetadata::_Internal {
 public:
};

NodeMetadata::NodeMetadata(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Habitify.Communication.NodeMetadata)
}
NodeMetadata::NodeMetadata(const NodeMetadata& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  NodeMetadata* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Habitify.Communication.NodeMetadata)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NodeMetadata::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NodeMetadata::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata NodeMetadata::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Habitify_5fprotocol_2eproto_getter, &descriptor_table_Habitify_5fprotocol_2eproto_once,
      file_level_metadata_Habitify_5fprotocol_2eproto[1]);
}

// ===================================================================

class NodeData::_Internal {
 public:
};

NodeData::NodeData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Habitify.Communication.NodeData)
}
NodeData::NodeData(const NodeData& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  NodeData* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Habitify.Communication.NodeData)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NodeData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NodeData::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata NodeData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Habitify_5fprotocol_2eproto_getter, &descriptor_table_Habitify_5fprotocol_2eproto_once,
      file_level_metadata_Habitify_5fprotocol_2eproto[2]);
}

// ===================================================================

class Id::_Internal {
 public:
};

Id::Id(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Habitify.Communication.Id)
}
Id::Id(const Id& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Id* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Habitify.Communication.Id)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Id::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Id::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Id::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Habitify_5fprotocol_2eproto_getter, &descriptor_table_Habitify_5fprotocol_2eproto_once,
      file_level_metadata_Habitify_5fprotocol_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Communication
}  // namespace Habitify
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Habitify::Communication::Node*
Arena::CreateMaybeMessage< ::Habitify::Communication::Node >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Habitify::Communication::Node >(arena);
}
template<> PROTOBUF_NOINLINE ::Habitify::Communication::NodeMetadata*
Arena::CreateMaybeMessage< ::Habitify::Communication::NodeMetadata >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Habitify::Communication::NodeMetadata >(arena);
}
template<> PROTOBUF_NOINLINE ::Habitify::Communication::NodeData*
Arena::CreateMaybeMessage< ::Habitify::Communication::NodeData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Habitify::Communication::NodeData >(arena);
}
template<> PROTOBUF_NOINLINE ::Habitify::Communication::Id*
Arena::CreateMaybeMessage< ::Habitify::Communication::Id >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Habitify::Communication::Id >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
