// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Habitify_protocol.proto

#include "Habitify_protocol.pb.h"
#include "Habitify_protocol.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace Habitify {
namespace Communication {

static const char* HabitifyServer_method_names[] = {
  "/Habitify.Communication.HabitifyServer/Ping",
};

std::unique_ptr< HabitifyServer::Stub> HabitifyServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HabitifyServer::Stub> stub(new HabitifyServer::Stub(channel, options));
  return stub;
}

HabitifyServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Ping_(HabitifyServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HabitifyServer::Stub::Ping(::grpc::ClientContext* context, const ::Habitify::Communication::Id& request, ::Habitify::Communication::Id* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Habitify::Communication::Id, ::Habitify::Communication::Id, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void HabitifyServer::Stub::async::Ping(::grpc::ClientContext* context, const ::Habitify::Communication::Id* request, ::Habitify::Communication::Id* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Habitify::Communication::Id, ::Habitify::Communication::Id, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void HabitifyServer::Stub::async::Ping(::grpc::ClientContext* context, const ::Habitify::Communication::Id* request, ::Habitify::Communication::Id* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Habitify::Communication::Id>* HabitifyServer::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::Habitify::Communication::Id& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Habitify::Communication::Id, ::Habitify::Communication::Id, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Habitify::Communication::Id>* HabitifyServer::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::Habitify::Communication::Id& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

HabitifyServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HabitifyServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HabitifyServer::Service, ::Habitify::Communication::Id, ::Habitify::Communication::Id, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HabitifyServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Habitify::Communication::Id* req,
             ::Habitify::Communication::Id* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
}

HabitifyServer::Service::~Service() {
}

::grpc::Status HabitifyServer::Service::Ping(::grpc::ServerContext* context, const ::Habitify::Communication::Id* request, ::Habitify::Communication::Id* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Habitify
}  // namespace Communication

